import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import HuddleApp from "./Component/HuddleApp";
import "@aws-amplify/ui-react/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>      
        <HuddleApp>
          {children}
        </HuddleApp>
      </body>
    </html>
  );
}
